// AUTO-GENERATED FILE - DO NOT EDIT
import { DomainCategory } from '../../types/workspace';

export const TEMPLATES: Record<DomainCategory, Record<string, string>> = {
  WEB_APP: {
    '/01_Overview.md': "# Web App: Project Overview\r\n\r\n## Product Vision & Goals\r\n*   **Mission:** Build a high-performance, web-based application delivering responsive desktop-grade functionality.\r\n*   **Target Audience:** General web users accessing via standard desktop and mobile browsers.\r\n*   **Success Metrics:** Page load speed < 1.5s, User Retention rate > 40%, System Uptime > 99.9%.\r\n\r\n## Platform Requirements\r\n*   **Browser Compatibility:** Chrome (last 3 versions), Firefox, Safari (last 2 versions), Edge.\r\n*   **Responsive Breakpoints:** Mobile-first media queries:\r\n    *   Mobile: < 768px\r\n    *   Tablet: 768px - 1024px\r\n    *   Desktop: > 1024px\r\n*   **Accessibility Standards:** Conform to WCAG 2.1 Level AA requirements.",
    '/02_Features.md': "# Web App: Product Features & Requirements\r\n\r\n## Core Functional Specs\r\n### 1. User Dashboard\r\n*   **Objective:** Provide a centralized view of user data, notifications, and active sessions.\r\n*   **Features:** Drag-and-drop widgets, customizable search filters, export data button.\r\n*   **Permissions:** Viewable by logged-in users only.\r\n\r\n### 2. File Explorer & Editor\r\n*   **Objective:** Enable inline file organization and editing directly in-browser.\r\n*   **Features:** Create, rename, delete files. File tree visualization on sidebar.\r\n*   **Autosave:** Trigger every 300ms of inactivity.\r\n\r\n## User Persona Profiles\r\n*   **Product Managers:** Need macro-level project dashboards and export tools.\r\n*   **Developers:** Require fast UI response times, inline markdown editors, and clear API metrics.",
    '/03_Architecture.md': "# Web App: Architecture Blueprint\r\n\r\n## Technology Stack\r\n*   **Frontend Framework:** Next.js (React 18), Tailwind CSS, TypeScript.\r\n*   **State Management:** Zustand with custom middleware.\r\n*   **Database:** PostgreSQL for primary storage, Redis for session caching.\r\n*   **Authentication:** OAuth 2.0 / OpenID Connect (Google, GitHub, email).\r\n\r\n## Caching Strategy\r\n*   **Client Cache:** Stale-While-Revalidate (SWR) fetching strategy.\r\n*   **Edge Cache:** Vercel Edge Middleware for localized routing.\r\n*   **Server Cache:** Redis cluster for session states and rate limits.",
    '/04_API_Endpoints.md': "# Web App: API & Integration Spec\r\n\r\n## Endpoint Specifications (v1)\r\n*   GET /api/v1/workspaces\r\n    *   *Description:* Retrieves a list of active workspaces for the authenticated user.\r\n    *   *Response (200):* { workspaces: Workspace[] }\r\n*   POST /api/v1/workspaces\r\n    *   *Description:* Creates a new workspace under the user's account.\r\n    *   *Payload:* { name: string, category: string }\r\n*   DELETE /api/v1/workspaces/:id\r\n    *   *Description:* Destroys a workspace and its associated conversation log.\r\n\r\n## Rate Limiting & Safety\r\n*   Standard endpoints capped at 100 requests per minute per IP address.\r\n*   Error payloads follow the RFC 7807 problem details specification.",
    '/05_UI_UX_Specification.md': "# Web App: UI/UX Specification\r\n\r\n## Design System Tokens\r\n*   **Colors:**\r\n    *   Primary: Indigo (#6366f1)\r\n    *   Secondary: Violet (#8b5cf6)\r\n    *   Neutral Background: Dark slate (#0f172a)\r\n*   **Typography:** Inter (main body font), JetBrains Mono (monospace coding blocks).\r\n\r\n## Key User Flows\r\n1.  **Onboarding:** Login -> Select Template -> Initialize Workspace.\r\n2.  **Document Drafting:** Select File -> Input Text -> Real-time preview updates on split-pane.",
    '/06_Deployment_Ops.md': "# Web App: Deployment & Ops\r\n\r\n## CI/CD Pipeline\r\n*   **Trigger:** Merges into the main branch.\r\n*   **Pipeline Steps:** Lint -> Format Verification -> Build Checks -> Integration Tests -> Vercel Deployment.\r\n\r\n## Monitoring & Alerts\r\n*   **Performance Tracking:** Vercel Analytics + Speed Insights.\r\n*   **Error Logging:** Sentry SDK integration for client-side crash tracking.\r\n*   **Backup Strategy:** Automated daily PostgreSQL backups stored securely on AWS S3 with 30-day retention.",
  },
  NATIVE_DESKTOP: {
    '/01_Overview.md': "# Desktop App: Project Overview\r\n\r\n## Core Objectives\r\n*   **Mission:** Build a high-performance native desktop tool that operates client-side with native filesystem access.\r\n*   **Target OS Platform:** Windows 10/11, macOS Monterey+, Ubuntu 22.04 LTS+.\r\n*   **Success Metrics:** Idle memory < 150MB, App cold startup time < 1.5 seconds.\r\n\r\n## Architecture Paradigm\r\n*   **Shell Engine:** Tauri (Rust backend, HTML/TS frontend).\r\n*   **Storage Approach:** Local-first SQLite database.\r\n*   **Process Isolation:** Main native process handles OS APIs; Renderer process runs sandbox UI.",
    '/02_Features.md': "# Desktop App: Core Native Features\r\n\r\n## File System Integration\r\n*   **System Files:** Full read/write capability to designated workspace directories.\r\n*   **Native Dialogs:** OS file pickers for choosing folder directories and opening archives.\r\n*   **Watcher API:** Real-time hot-reloading when files are edited outside the application shell.\r\n\r\n## Offline Mode Requirements\r\n*   **Zero Network Sync:** Full functionality when disconnected.\r\n*   **Conflict Resolution:** Local file system modifications override remote states.\r\n*   **Local Engine:** Inline AI parsing via local llama.cpp endpoints when offline.",
    '/03_Architecture.md': "# Desktop App: Multi-Process Architecture\r\n\r\n## Process Communication (IPC)\r\n*   Frontend triggers Rust bindings using secure commands: invoke('create_file', { path: string }).\r\n*   Rust main process listens, executes system actions, and returns strongly-typed results.\r\n\r\n## Data Schema & Local DB\r\n*   **Engine:** SQLite (via sqlx in Rust).\r\n*   **Migrations:** Embedded SQL scripts executed automatically on startup.\r\n*   **Tables:** Workspaces, FileIndex, LocalConfig, ChatHistory.",
    '/04_System_Integration.md': "# Desktop App: OS Integration Spec\r\n\r\n## Menu & Tray Features\r\n*   **Native Menus:** Custom system file menus (File, Edit, View, AI Assistant).\r\n*   **System Tray:** Background polling options, quick-scratchpad menu, and application restore button.\r\n\r\n## File Associations\r\n*   Automatically register app as default handler for .cprd and .md extensions.\r\n*   Support drag-and-drop file operations directly onto the active app workspace.",
    '/05_Performance_Metrics.md': "# Desktop App: Performance Targets\r\n\r\n## Benchmarks\r\n*   **Frame Render Budget:** < 16.6ms (solid 60 FPS) under heavy layouts.\r\n*   **File Read/Load:** < 100ms for loading files larger than 10MB.\r\n*   **Local Search Indexing:** < 500ms for indexing 15,000 document files.\r\n\r\n## Memory Optimization\r\n*   Avoid memory leaks by terminating unused background webview instances.\r\n*   Employ virtual list rendering for sidebar trees and active text views.",
    '/06_Security_Compliance.md': "# Desktop App: Security & Code Signing\r\n\r\n## Application Notarization\r\n*   **macOS:** Automated notarization using Apple Developer tools during pipeline build.\r\n*   **Windows:** EV Code Signing certificate signature to prevent Windows SmartScreen alerts.\r\n\r\n## Sandboxing\r\n*   Restrict IPC commands to prevent arbitrary execution of shell files.\r\n*   Disable native developer tools in production releases.\r\n*   Encrypt application configuration files at rest.",
  },
  MOBILE_APP: {
    '/01_Overview.md': "# Mobile App: Project Overview\r\n\r\n## Core Objectives\r\n*   **Mission:** Deliver an offline-first companion mobile app designed for editing PRDs and managing workspaces on-the-go.\r\n*   **Platform Targets:** iOS 16.0+, Android 13.0+.\r\n*   **Success Metrics:** App crash-free rate > 99.9%, Touch interaction lag < 100ms.\r\n\r\n## Development Framework\r\n*   **Tech Stack:** React Native (TypeScript), Expo SDK, Reanimated.\r\n*   **Local Store:** WatermelonDB / SQLite.",
    '/02_Features.md': "# Mobile App: Native Mobile Features\r\n\r\n## Mobile Touch & Layout\r\n*   **Touch Targets:** Minimum 48x48dp for all buttons and interactive items.\r\n*   **Gestures:** Swipe left to delete conversation, pull-to-refresh folder structure.\r\n*   **Biometrics:** Optional Face ID / Fingerprint scanner login validation.\r\n\r\n## Mobile Offline Capability\r\n*   Cache all workspace data locally.\r\n*   Queue offline mutations (renaming, deleting) and play them back sequentially when connectivity returns.",
    '/03_Architecture.md': "# Mobile App: Architecture & Sync\r\n\r\n## Synchronization Architecture\r\n*   Client maintains dynamic sync status (Syncing, Up-to-date, Offline, Sync Error).\r\n*   API payload structures match JSON-patches to reduce mobile bandwidth payload sizes.\r\n\r\n## Data Persistence\r\n*   Structured data saved to SQLite.\r\n*   Large markdown files saved to local sandboxed app document directory.\r\n*   OAuth tokens stored securely via iOS Keychain / Android Keystore.",
    '/04_Push_Notifications.md': "# Mobile App: Push Notifications & Deep Linking\r\n\r\n## Notification Pipelines\r\n*   **Apple APNS:** Configure certificates for production distribution.\r\n*   **Google FCM:** Configure JSON file in project root.\r\n*   **Trigger Events:** Background document updates, team comment mentions, sync warnings.\r\n\r\n## Deep Linking Configuration\r\n*   **Custom Scheme:** contextprd://\r\n*   **Universal Links:** https://app.contextprd.com/workspace/* to bypass web page routes.",
    '/05_Sync_Conflict_Strategy.md': "# Mobile App: Sync Conflict Resolution\r\n\r\n## Conflict Scenarios\r\n1.  **Simultaneous Edit:** User edits a document on desktop and mobile offline.\r\n2.  **Workspace Deleted:** Mobile updates deleted workspace files.\r\n\r\n## Resolution Mechanics\r\n*   We employ a Last-Write-Wins (LWW) conflict strategy based on system timestamps.\r\n*   User will be prompted with a choice dialog in the UI if conflicts exceed 24 hours in age.",
    '/06_App_Store_Compliance.md': "# Mobile App: App Store Compliance\r\n\r\n## Apple Review Guardrails\r\n*   Must provide standard sign-in credentials for Apple Reviewers.\r\n*   Privacy Manifest must declare use of local document directories.\r\n*   Explicit App Tracking Transparency (ATT) prompt implementation if tracking analytics.\r\n\r\n## Google Play Guardrails\r\n*   Target SDK level maintained at the latest requirements (API 34+).\r\n*   Explicit permissions request model for runtime Push Notifications.",
  },
  GENERAL_SAAS: {
    '/01_Overview.md': "# B2B SaaS: Project Overview\r\n\r\n## Core Value Proposition\r\n*   **Mission:** Scale workspaces into collaborative multi-tenant team portals.\r\n*   **Key Users:** Enterprise Product Teams, Remote Startups, Software Development Agencies.\r\n*   **Success Metrics:** Active Tenant growth, Net Revenue Retention (NRR) > 115%.\r\n\r\n## Multi-Tenancy Architecture\r\n*   Logical data separation within a single unified database.\r\n*   Strict Role-Based Access Control (RBAC) layers (Admin, Member, Viewer).",
    '/02_Billing_Subscription.md': "# B2B SaaS: Billing & Subscription Specs\r\n\r\n## Stripe Billing Strategy\r\n*   **Pricing Tiers:** Free, Pro (/mo), Enterprise (/user/mo).\r\n*   **Provisioning Flow:** Stripe Webhook -> Parse Event -> Update Tenant License in Database -> Active/Block Workspace capabilities.\r\n\r\n## Customer Billing Portal\r\n*   Integrate Stripe Customer Portal link inside settings UI.\r\n*   Allow users to download invoices, upgrade tiers, and add billing info.",
    '/03_Data_Model.md': "# B2B SaaS: Data Schema & Isolation\r\n\r\n## Core PostgreSQL Schema\r\n*   **Tenants:** id, name, plan, status, stripe_customer_id, created_at\r\n*   **Workspaces:** id, tenant_id, name, profile, file_tree, created_at\r\n*   **Users:** id, tenant_id, email, password_hash, role, created_at\r\n\r\n## Tenant Isolation Guardrails\r\n*   Utilize PostgreSQL Row-Level Security (RLS) policies on all tenant tables.\r\n*   Database connection pooling configured with separate schemas for Enterprise tier.",
    '/04_Integration_API.md': "# B2B SaaS: Integrations & Webhooks\r\n\r\n## Developer API Specifications\r\n*   API key generation UI inside user profiles.\r\n*   All endpoints require bearer token authentication headers.\r\n*   Versioned endpoints (/api/v1/) returning standardized JSON formats.\r\n\r\n## Outbound Webhooks\r\n*   Post payloads on workspace actions (workspace.created, document.updated).\r\n*   HMAC-SHA256 headers generated to sign webhook payloads for verified client consumption.",
    '/05_Security_Compliance.md': "# B2B SaaS: Compliance & Security Guardrails\r\n\r\n## Data Compliance Targets\r\n*   **SOC 2 Type II:** Keep access logs, enforce password policies, maintain patch schedules.\r\n*   **GDPR:** Support user data deletion requests, local data hosting options (EU server cluster).\r\n\r\n## Security Audits\r\n*   Encrypt all database storage at rest using AES-256.\r\n*   Run weekly automated package vulnerability scans in CI/CD pipeline.",
    '/06_SLA_Infrastructure.md': "# B2B SaaS: SLA & Cloud Infrastructure\r\n\r\n## High Availability Setup\r\n*   Multiple application instances balanced with AWS ALB.\r\n*   Auto-scaling groups triggered when CPU exceeds 70%.\r\n*   99.9% uptime SLA commitments for Enterprise customer levels.\r\n\r\n## Disaster Recovery\r\n*   Continuous database replication with RDS Multi-AZ.\r\n*   Point-in-Time Recovery (PITR) backups with a 15-minute granularity target.",
  },
};
