// AUTO-GENERATED FILE - DO NOT EDIT
import { DomainCategory } from '../../types/workspace';

export const TEMPLATES: Record<DomainCategory, Record<string, string>> = {
  WEB_APP: {
    '/API_Endpoints.md': "# Web App: API & Integration Spec\n\n## Endpoint Specifications (v1)\n*   GET /api/v1/workspaces\n    *   *Description:* Retrieves a list of active workspaces for the authenticated user.\n    *   *Response (200):* { workspaces: Workspace[] }\n*   POST /api/v1/workspaces\n    *   *Description:* Creates a new workspace under the user's account.\n    *   *Payload:* { name: string, category: string }\n*   DELETE /api/v1/workspaces/:id\n    *   *Description:* Destroys a workspace and its associated conversation log.\n\n## Rate Limiting & Safety\n*   Standard endpoints capped at 100 requests per minute per IP address.\n*   Error payloads follow the RFC 7807 problem details specification.",
    '/Architecture.md': "# Web App: Architecture Blueprint\n\n## Technology Stack\n*   **Frontend Framework:** Next.js (React 18), Tailwind CSS, TypeScript.\n*   **State Management:** Zustand with custom middleware.\n*   **Database:** PostgreSQL for primary storage, Redis for session caching.\n*   **Authentication:** OAuth 2.0 / OpenID Connect (Google, GitHub, email).\n\n## Caching Strategy\n*   **Client Cache:** Stale-While-Revalidate (SWR) fetching strategy.\n*   **Edge Cache:** Vercel Edge Middleware for localized routing.\n*   **Server Cache:** Redis cluster for session states and rate limits.",
    '/Deployment_Ops.md': "# Web App: Deployment & Ops\n\n## CI/CD Pipeline\n*   **Trigger:** Merges into the main branch.\n*   **Pipeline Steps:** Lint -> Format Verification -> Build Checks -> Integration Tests -> Vercel Deployment.\n\n## Monitoring & Alerts\n*   **Performance Tracking:** Vercel Analytics + Speed Insights.\n*   **Error Logging:** Sentry SDK integration for client-side crash tracking.\n*   **Backup Strategy:** Automated daily PostgreSQL backups stored securely on AWS S3 with 30-day retention.",
    '/Features.md': "# Web App: Product Features & Requirements\n\n## Core Functional Specs\n### 1. User Dashboard\n*   **Objective:** Provide a centralized view of user data, notifications, and active sessions.\n*   **Features:** Drag-and-drop widgets, customizable search filters, export data button.\n*   **Permissions:** Viewable by logged-in users only.\n\n### 2. File Explorer & Editor\n*   **Objective:** Enable inline file organization and editing directly in-browser.\n*   **Features:** Create, rename, delete files. File tree visualization on sidebar.\n*   **Autosave:** Trigger every 300ms of inactivity.\n\n## User Persona Profiles\n*   **Product Managers:** Need macro-level project dashboards and export tools.\n*   **Developers:** Require fast UI response times, inline markdown editors, and clear API metrics.",
    '/Overview.md': "# Web App: Project Overview\n\n## Product Vision & Goals\n*   **Mission:** Build a high-performance, web-based application delivering responsive desktop-grade functionality.\n*   **Target Audience:** General web users accessing via standard desktop and mobile browsers.\n*   **Success Metrics:** Page load speed < 1.5s, User Retention rate > 40%, System Uptime > 99.9%.\n\n## Platform Requirements\n*   **Browser Compatibility:** Chrome (last 3 versions), Firefox, Safari (last 2 versions), Edge.\n*   **Responsive Breakpoints:** Mobile-first media queries:\n    *   Mobile: < 768px\n    *   Tablet: 768px - 1024px\n    *   Desktop: > 1024px\n*   **Accessibility Standards:** Conform to WCAG 2.1 Level AA requirements.",
    '/UI_UX_Specification.md': "# Web App: UI/UX Specification\n\n## Design System Tokens\n*   **Colors:**\n    *   Primary: Indigo (#6366f1)\n    *   Secondary: Violet (#8b5cf6)\n    *   Neutral Background: Dark slate (#0f172a)\n*   **Typography:** Inter (main body font), JetBrains Mono (monospace coding blocks).\n\n## Key User Flows\n1.  **Onboarding:** Login -> Select Template -> Initialize Workspace.\n2.  **Document Drafting:** Select File -> Input Text -> Real-time preview updates on split-pane.",
  },
  NATIVE_DESKTOP: {
    '/Architecture.md': "# Desktop App: Multi-Process Architecture\n\n## Process Communication (IPC)\n*   Frontend triggers Rust bindings using secure commands: invoke('create_file', { path: string }).\n*   Rust main process listens, executes system actions, and returns strongly-typed results.\n\n## Data Schema & Local DB\n*   **Engine:** SQLite (via sqlx in Rust).\n*   **Migrations:** Embedded SQL scripts executed automatically on startup.\n*   **Tables:** Workspaces, FileIndex, LocalConfig, ChatHistory.",
    '/Features.md': "# Desktop App: Core Native Features\n\n## File System Integration\n*   **System Files:** Full read/write capability to designated workspace directories.\n*   **Native Dialogs:** OS file pickers for choosing folder directories and opening archives.\n*   **Watcher API:** Real-time hot-reloading when files are edited outside the application shell.\n\n## Offline Mode Requirements\n*   **Zero Network Sync:** Full functionality when disconnected.\n*   **Conflict Resolution:** Local file system modifications override remote states.\n*   **Local Engine:** Inline AI parsing via local llama.cpp endpoints when offline.",
    '/Overview.md': "# Desktop App: Project Overview\n\n## Core Objectives\n*   **Mission:** Build a high-performance native desktop tool that operates client-side with native filesystem access.\n*   **Target OS Platform:** Windows 10/11, macOS Monterey+, Ubuntu 22.04 LTS+.\n*   **Success Metrics:** Idle memory < 150MB, App cold startup time < 1.5 seconds.\n\n## Architecture Paradigm\n*   **Shell Engine:** Tauri (Rust backend, HTML/TS frontend).\n*   **Storage Approach:** Local-first SQLite database.\n*   **Process Isolation:** Main native process handles OS APIs; Renderer process runs sandbox UI.",
    '/Performance_Metrics.md': "# Desktop App: Performance Targets\n\n## Benchmarks\n*   **Frame Render Budget:** < 16.6ms (solid 60 FPS) under heavy layouts.\n*   **File Read/Load:** < 100ms for loading files larger than 10MB.\n*   **Local Search Indexing:** < 500ms for indexing 15,000 document files.\n\n## Memory Optimization\n*   Avoid memory leaks by terminating unused background webview instances.\n*   Employ virtual list rendering for sidebar trees and active text views.",
    '/Security_Compliance.md': "# Desktop App: Security & Code Signing\n\n## Application Notarization\n*   **macOS:** Automated notarization using Apple Developer tools during pipeline build.\n*   **Windows:** EV Code Signing certificate signature to prevent Windows SmartScreen alerts.\n\n## Sandboxing\n*   Restrict IPC commands to prevent arbitrary execution of shell files.\n*   Disable native developer tools in production releases.\n*   Encrypt application configuration files at rest.",
    '/System_Integration.md': "# Desktop App: OS Integration Spec\n\n## Menu & Tray Features\n*   **Native Menus:** Custom system file menus (File, Edit, View, AI Assistant).\n*   **System Tray:** Background polling options, quick-scratchpad menu, and application restore button.\n\n## File Associations\n*   Automatically register app as default handler for .cprd and .md extensions.\n*   Support drag-and-drop file operations directly onto the active app workspace.",
  },
  MOBILE_APP: {
    '/App_Store_Compliance.md': "# Mobile App: App Store Compliance\n\n## Apple Review Guardrails\n*   Must provide standard sign-in credentials for Apple Reviewers.\n*   Privacy Manifest must declare use of local document directories.\n*   Explicit App Tracking Transparency (ATT) prompt implementation if tracking analytics.\n\n## Google Play Guardrails\n*   Target SDK level maintained at the latest requirements (API 34+).\n*   Explicit permissions request model for runtime Push Notifications.",
    '/Architecture.md': "# Mobile App: Architecture & Sync\n\n## Synchronization Architecture\n*   Client maintains dynamic sync status (Syncing, Up-to-date, Offline, Sync Error).\n*   API payload structures match JSON-patches to reduce mobile bandwidth payload sizes.\n\n## Data Persistence\n*   Structured data saved to SQLite.\n*   Large markdown files saved to local sandboxed app document directory.\n*   OAuth tokens stored securely via iOS Keychain / Android Keystore.",
    '/Features.md': "# Mobile App: Native Mobile Features\n\n## Mobile Touch & Layout\n*   **Touch Targets:** Minimum 48x48dp for all buttons and interactive items.\n*   **Gestures:** Swipe left to delete conversation, pull-to-refresh folder structure.\n*   **Biometrics:** Optional Face ID / Fingerprint scanner login validation.\n\n## Mobile Offline Capability\n*   Cache all workspace data locally.\n*   Queue offline mutations (renaming, deleting) and play them back sequentially when connectivity returns.",
    '/Overview.md': "# Mobile App: Project Overview\n\n## Core Objectives\n*   **Mission:** Deliver an offline-first companion mobile app designed for editing PRDs and managing workspaces on-the-go.\n*   **Platform Targets:** iOS 16.0+, Android 13.0+.\n*   **Success Metrics:** App crash-free rate > 99.9%, Touch interaction lag < 100ms.\n\n## Development Framework\n*   **Tech Stack:** React Native (TypeScript), Expo SDK, Reanimated.\n*   **Local Store:** WatermelonDB / SQLite.",
    '/Push_Notifications.md': "# Mobile App: Push Notifications & Deep Linking\n\n## Notification Pipelines\n*   **Apple APNS:** Configure certificates for production distribution.\n*   **Google FCM:** Configure JSON file in project root.\n*   **Trigger Events:** Background document updates, team comment mentions, sync warnings.\n\n## Deep Linking Configuration\n*   **Custom Scheme:** contextprd://\n*   **Universal Links:** https://app.contextprd.com/workspace/* to bypass web page routes.",
    '/Sync_Conflict_Strategy.md': "# Mobile App: Sync Conflict Resolution\n\n## Conflict Scenarios\n1.  **Simultaneous Edit:** User edits a document on desktop and mobile offline.\n2.  **Workspace Deleted:** Mobile updates deleted workspace files.\n\n## Resolution Mechanics\n*   We employ a Last-Write-Wins (LWW) conflict strategy based on system timestamps.\n*   User will be prompted with a choice dialog in the UI if conflicts exceed 24 hours in age.",
  },
  GENERAL_SAAS: {
    '/Billing_Subscription.md': "# B2B SaaS: Billing & Subscription Specs\n\n## Stripe Billing Strategy\n*   **Pricing Tiers:** Free, Pro (/mo), Enterprise (/user/mo).\n*   **Provisioning Flow:** Stripe Webhook -> Parse Event -> Update Tenant License in Database -> Active/Block Workspace capabilities.\n\n## Customer Billing Portal\n*   Integrate Stripe Customer Portal link inside settings UI.\n*   Allow users to download invoices, upgrade tiers, and add billing info.",
    '/Data_Model.md': "# B2B SaaS: Data Schema & Isolation\n\n## Core PostgreSQL Schema\n*   **Tenants:** id, name, plan, status, stripe_customer_id, created_at\n*   **Workspaces:** id, tenant_id, name, profile, file_tree, created_at\n*   **Users:** id, tenant_id, email, password_hash, role, created_at\n\n## Tenant Isolation Guardrails\n*   Utilize PostgreSQL Row-Level Security (RLS) policies on all tenant tables.\n*   Database connection pooling configured with separate schemas for Enterprise tier.",
    '/Integration_API.md': "# B2B SaaS: Integrations & Webhooks\n\n## Developer API Specifications\n*   API key generation UI inside user profiles.\n*   All endpoints require bearer token authentication headers.\n*   Versioned endpoints (/api/v1/) returning standardized JSON formats.\n\n## Outbound Webhooks\n*   Post payloads on workspace actions (workspace.created, document.updated).\n*   HMAC-SHA256 headers generated to sign webhook payloads for verified client consumption.",
    '/Overview.md': "# B2B SaaS: Project Overview\n\n## Core Value Proposition\n*   **Mission:** Scale workspaces into collaborative multi-tenant team portals.\n*   **Key Users:** Enterprise Product Teams, Remote Startups, Software Development Agencies.\n*   **Success Metrics:** Active Tenant growth, Net Revenue Retention (NRR) > 115%.\n\n## Multi-Tenancy Architecture\n*   Logical data separation within a single unified database.\n*   Strict Role-Based Access Control (RBAC) layers (Admin, Member, Viewer).",
    '/Security_Compliance.md': "# B2B SaaS: Compliance & Security Guardrails\n\n## Data Compliance Targets\n*   **SOC 2 Type II:** Keep access logs, enforce password policies, maintain patch schedules.\n*   **GDPR:** Support user data deletion requests, local data hosting options (EU server cluster).\n\n## Security Audits\n*   Encrypt all database storage at rest using AES-256.\n*   Run weekly automated package vulnerability scans in CI/CD pipeline.",
    '/SLA_Infrastructure.md': "# B2B SaaS: SLA & Cloud Infrastructure\n\n## High Availability Setup\n*   Multiple application instances balanced with AWS ALB.\n*   Auto-scaling groups triggered when CPU exceeds 70%.\n*   99.9% uptime SLA commitments for Enterprise customer levels.\n\n## Disaster Recovery\n*   Continuous database replication with RDS Multi-AZ.\n*   Point-in-Time Recovery (PITR) backups with a 15-minute granularity target.",
  },
};
